apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: argo-certificate
  namespace: istio-ingress
spec:
  dnsNames:
    - demo-app.invisitr.com
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-prod
  secretName: demo-app-certificate
