apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: rollouts-demo-certificate
  namespace: istio-ingress
spec:
  dnsNames:
    - rollouts-demo.invisitr.com
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-prod
  secretName: rollouts-demo-certificate
