apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml
- gateways.yaml
- services.yaml
- virtualservices.yaml
- rollout.yaml
- certificates.yaml

configurations:
- https://argoproj.github.io/argo-rollouts/features/kustomize/rollout-transform.yaml