apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: argo-workflows
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - cluster: in-cluster
            url: https://kubernetes.default.svc
  template:
    metadata:
      name: argo-workflows
    spec:
      destination:
        namespace: argo
        server: '{{url}}'
      project: default
      source:
        directory:
          recurse: true
        path: workflows
        repoURL: git@github.com:aboutflying/DigitalOcean-kubernetes-challenge-2021.git
        targetRevision: HEAD
      syncPolicy:
        automated:
          prune: false