apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: buildkit-runner
spec:
  entrypoint: buildkit-runner
  ttlStrategy:
    secondsAfterCompletion: 300 # Time to live after workflow is completed
  # a temporary volume, named workdir, will be used as a working directory
  # for this workflow. This volume is passed around from step to step.
  volumeClaimTemplates:
  - metadata:
      name: workdir
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi

  templates:
  - name: buildkit-runner
    inputs:
      parameters:
      - name: revision
    steps:
    - - name: get-version
        template: get-version
    - - name: build
        template: buildkit-build

  - name: get-version
    inputs:
      parameters:
      - name: revision
        value: "{{workflow.parameters.revision}}"
      artifacts:
      - name: code
        path: /workdir/src
        git:
          repo: https://github.com/aboutflying/DigitalOcean-kubernetes-challenge-2021.git
          revision: "{{inputs.parameters.revision}}"
    container:
      image: stedolan/jq
      command: [sh, -c]
      args: ["/usr/local/bin/jq -r .version /workdir/src/node-demo-app/package.json | tee /workdir/src/node-demo-app/version"]
      volumeMounts:
      - name: workdir
        mountPath: /workdir
    outputs:
      parameters:
        - name: version
          valueFrom:
            path: /workdir/src/node-demo-app/version
  - name: buildkit-build
    inputs:
      parameters:
      - name: version
        value: "{{steps.get-version.outputs.parameters.version}}"
    volumes:
      - name: docker-config
        secret:
          secretName: docker-config
    container:
      image: moby/buildkit:master
      command:
        - buildctl-daemonless.sh
      args: 
        - build
        - --frontend
        - dockerfile.v0
        - --local
        - context=/workdir/src/node-demo-app
        - --local
        - dockerfile=/workdir/src/node-demo-app
        - --output
        - type=image,"name=docker.io/invisitr/node-demo-app:{{inputs.parameters.version}}",push=true
      env:
        - name: DOCKER_CONFIG
          value: /.docker
      volumeMounts:
      - name: workdir
        mountPath: /workdir
      - name: docker-config
        mountPath: /.docker
      securityContext:
        privileged: true
---
apiVersion: argoproj.io/v1alpha1
kind: WorkflowEventBinding
metadata:
  name: node-demo-app-event
spec:
  event:
    selector: payload.head_commit.message != "" && (payload.head_commit.message contains "*build*")
  submit:
    workflowTemplateRef:
      name: buildkit-runner
    arguments:
      parameters:
      - name: revision
        valueFrom:
          event: payload.head_commit.id