apiVersion: v1
kind: Service
metadata:
  name: node-demo-app
  namespace: node-demo-app
  labels:
    app: node-demo-app
spec:
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
    name: http
  selector:
    app: node-demo-app
---
apiVersion: v1
kind: Service
metadata:
  name: node-demo-app-vnext
  namespace: node-demo-app
  labels:
    app: node-demo-app
spec:
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
    name: http
  selector:
    app: node-demo-app

